### ISSUE TITLE
Publish library to maven repository

### ISSUE THREAD

**Issue by robertoschwald** [wrandelshofer/MonteMedia#2]
Currently, I can only find (old or different versioned) forks of your library on maven.org, like ru.sbtqa (https://github.com/sbtqa/monte-media)

It would be greatly helpful if you can publish the library to the maven central repository, so adopters can use it in their Maven / Gradle projects.

Thanks.

**Comment by wrandelshofer** [comment]
I made a new release 2.0 of MonteMedia, which includes POM files.

I have not published it yet on Maven Central, because is not clear to me, how many POM files are needed for a modular release of MonteMedia with the Java 9 module system.
I'll drop a note when I have figured this out.

**Comment by eduyayo** [comment]
Any news on thiz?

**Comment by wrandelshofer** [comment]
I have published now version 17 on Maven Central.

I have made very small modules. So you will probably only need the thirst 3:

1. https://search.maven.org/artifact/ch.randelshofer/org.monte.media.screenrecorder/17/jar
2. https://search.maven.org/artifact/ch.randelshofer/org.monte.media/17/jar
3. https://search.maven.org/artifact/ch.randelshofer/org.monte.media.swing/17/jar
4. https://search.maven.org/artifact/ch.randelshofer/org.monte.media.jmf/17/jar
5. https://search.maven.org/artifact/ch.randelshofer/org.monte.media.amigaatari/17/jar
6. https://search.maven.org/artifact/ch.randelshofer/org.monte.media.javafx/17/jar
