### ISSUE TITLE
Are there any prerequisites for using this library?

### ISSUE THREAD

**Issue by d3v2a** [wrandelshofer/MonteMedia#5]
I tried to use your library but nothing work.

All my tests fail with the error : "Error no writer found for file format".

Same with your demo app.

Os: Linux mint 21.3

**Comment by wrandelshofer** [comment]
The library must be added to the module-path of the JVM. 
It does not work on the class-path.

**Comment by basil** [comment]
> The library must be added to the module-path of the JVM.
> It does not work on the class-path.

Pending #8

**Comment by wrandelshofer** [comment]
Thanks to the changes that basil has contributed to this library, a future version will also work on the class-path.
